name: ense885ay
channels:
- pytorch
- menpo
- defaults
dependencies:
- jupyter
- matplotlib
- python=3.5
- parso=0.7
- scikit-learn
- scipy
- opencv3
- vlfeat
- pytorch
- torchvision
- pip
- pip:
  - visdom
- pyyaml
